apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "quarkus-pact-contract-testing"
  description: quarkus pact contract testing
  annotations:
    backstage.io/kubernetes-id: quarkus-pact-contract-testing
    github.com/project-slug: fotisolgr/quarkus-pact-contract-testing
  tags:
    - quarkus
    - v0.1.0
    - v0.1.1
spec:
  type: service
  owner: user:fotisolgr
  lifecycle: experimental
  providesApis:
    - users-api
  consumesApis:
    - gcloud-api
