apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "quarkus-pact-contract-testing"
  description: quarkus pact contract testing
  annotations:
    backstage.io/kubernetes-id: quarkus-pact-contract-testing
    github.com/project-slug: fotisolgr/quarkus-pact-contract-testing
  tags:
    - quarkus
    - pact
spec:
  type: service
  owner: user:fotisolgr
  system: gemma
  lifecycle: experimental
  dependsOn:
    - component:default/tote
    - resource:default/postgres-db
  providesApis:
    - users-api
  consumesApis:
    - gcloud-api
