site_name: Quarkus pact contract testing documentation
repo_url: https://github.com/fotisolgr/quarkus-pact-contract-testing

nav:
  - Intro: 'index.md'
  - Contact: 'contact.md'
  - API:
    - v0.1.0: v0.1.0/reference.md
    - v0.1.1: v0.1.1/reference.md
    
plugins:
  - techdocs-core
  
theme:
  name: material
  features:
    - toc.integrate

markdown_extensions:
  - pymdownx.extra
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.smartsymbols
  - pymdownx.tasklist
